version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: "postgres:15.1-bullseye"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi

