version: "3.9"
services:
#
#  api:
#    build: .
#    ports:
#      - "8000:8000"
#    environment:
##      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
##      - DATABASE_PORT=${DATABASE_PORT}
##      - DATABASE_NAME=${DATABASE_NAME}
##      - DATABASE_USERNAME=${DATABASE_USERNAME}
##      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
##      - SECRET_KEY=${SECRET_KEY}
##      - ALGORITHM=${ALGORITHM}
##      - ACCESS_TOKEN_EXPIRE_MINUTES=6${ACCESS_TOKEN_EXPIRE}
#      - DATABASE_HOSTNAME=db
#      - DATABASE_PORT=5432
#      - DATABASE_NAME=fastapi
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=test
#      - SECRET_KEY=secret
#      - ALGORITHM=HS256
#      - ACCESS_TOKEN_EXPIRE_MINUTES=60
#    volumes:
#      - ./:/usr/src/app:ro
##    command:
##      - uvicorn aoo.main:app --host 0.0.0.0 --port 8000 --reload
#
#    restart: always
#    depends_on:
#      - db

  db:
    image: postgres:15.1
    ports:
      - '5432:5432'
    environment:
#      - POSTGRES_USER=${DATABASE_USERNAME}
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
#      - POSTGRES_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_ROOT_PASSWORD=test
      - POSTGRES_DB=fastapi
      - DB_HOST=127.0.0.1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-db: